version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: keke

archives:
  - format: tar.gz
    name_template: "keke_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "keke_checksums.txt"

release:
  github:
    owner: Aimable2002
    name: keke_aia
  draft: false
  prerelease: false
  name_template: "Keke v{{ .Version }}"
  
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"